name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags

      - name: Install dependencies
        run: |
	  docker pull crazymax/xgo:latest
          go install github.com/crazy-max/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          chmod +x ./build.sh
          bash build.sh -r b

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloudreve
          path: dist
