name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags

      - name: Get dependencies and build
        run: |
          sudo apt-get update -y
          sudo apt-get -y install gcc-mingw-w64-x86-64
          sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
          sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          chmod +x ./build.sh
          ./build.sh -r b

      - name: Upload binary files
        uses: actions/upload-artifact@v3
        with:
          name: cloudreve
          path: build