name: build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-20.04]
        go-version: [1.18]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          docker pull crazymax/xgo:latest
          go install github.com/crazy-max/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          bash build.sh -r b

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloudreve
          path: dist